name: CI Push Testing

on:
  push:
    branches:
      - "autopep8-patches/**"

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
    continue-on-error: true
    outputs:
      files_to_lint: ${{ steps.flake8.outputs.test }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v24

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install flake8
      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1

      - name: Lint with flake8
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == *.py ]]; then
              flake8 $file
            fi
          done
