name: CI Push Testing

on: [pull_request]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install flake8
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v24
      - name: Echo changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: Lint with flake8
        run: flake8 ${{ steps.changed-files.outputs.all_changed_files }}
        # continue-on-error: true
  core-unit:
    name: GangaCore Unit
    needs: lint
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3
        run: |
          yum install -y centos-release-scl-rh
          yum install -y rh-python38-python rh-python38-python-pip
      - name: Install dependencies
        run: |
          /opt/rh/rh-python38/root/usr/bin/python -m pip install --upgrade pip setuptools wheel
          /opt/rh/rh-python38/root/usr/bin/python -m pip install -e .[dev]
      - name: Test with pytest
        run: /opt/rh/rh-python38/root/usr/bin/python -m pytest --cov-report term-missing --cov ganga/GangaCore/Core --cov ganga/GangaCore/GPI --cov ganga/GangaCore/GPIDev --cov ganga/GangaCore/Lib --cov ganga/GangaCore/Runtime --cov ganga/GangaCore/PACKAGE.py --cov ganga/GangaCore/Utility --cov ganga/GangaCore/__init__.py ganga/GangaCore/test/Unit
